# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = u'Kamuee ユーザガイド'
copyright = u'2020, '
author = u''
author_ja = u''

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u'1.1 / 0.6.3t'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'
today = u'2020年4月22日'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Options for LaTeX output ---------------------------------------------

# 図表番号自動採番
numfig = True

latex_docclass = {'manual': 'jsbook', 'howto': 'article'}

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    'preamble': '''
\\usepackage{colortbl}
\\renewcommand{\\bibname}{参考文献}
\\renewcommand{\\contentsname}{目次}
    ''',
    # 'maketitle': '\\sphinxmaketitle',
    'releasename': 'Revision',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'tableofcontents': '''\\sphinxtableofcontents\\addcontentsline{toc}{chapter}{目次}''',
}

latex_documents = [
    ('index', 'kamuee-users-guide.tex', u'\\mbox{Kamuee Users Guide}',
      author, 'manual'),
]
